[workspace]
members = ["lib", "server"]
resolver = "2"

[workspace.dependencies]
uuid = { version = "1.19.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
