[workspace]
members = ["lib", "server"]
resolver = "2"

[workspace.dependencies]
rustc-hash = { version = "2.1.1" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
uuid = { version = "1.19.0", features = ["v4", "serde"] }
