[package]
name = "server"
version = "0.1.0"
edition = "2024"

[features]
default = []
fx-hash = ["dep:rustc-hash", "occlusion/fx-hash"]

[dependencies]
occlusion = { path = "../lib" }

clap = { version = "4.5.54", features = ["derive"] }
rocket = { version = "0.5", features = ["json"] }
rustc-hash = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
thiserror = { workspace = true }
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { workspace = true, features = ["v4", "serde"] }
