[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
occlusion = { path = "../lib" }

clap = { version = "4.5.54", features = ["derive"] }
rocket = { version = "0.5", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
thiserror = { workspace = true }
tokio = { version = "1.49.0", features = ["full"] }
uuid = { workspace = true, features = ["v4", "serde"] }
